---

- name: Configure nginx with tls
  hosts: webservers
  sudo: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key_file
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      apt: name=nginx update_cache=yes

    - name: Create directory for ssl certs
      file: path=/etc/nginx/ssl state=directory

    - name: Copy tls key
      copy: src=files/nginx.key dest={{ key_file}} owner=root mode=0600
      notify: restart nginx

    - name: copy tls certs
      copy: src=files/nginx.crt dest={{cert_file}}
      notify: restart nginx

    - name: copy nginx conf file
      template: src=files/nginx.conf dest={{conf_file}}
      notify: restart nginx

    - name: Enable conf file
      file: dest=/etc/nginx/sites-enabled/default src={{conf_file}} state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html dest=/usr/share/nginx/html/index.html mode=0644
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted